INSERT INTO day (name) VALUES ('MONDAY');
INSERT INTO day (name) VALUES ('TUESDAY');
INSERT INTO day (name) VALUES ('WEDNESDAY');
INSERT INTO day (name) VALUES ('THURSDAY');
INSERT INTO day (name) VALUES ('FRIDAY');
INSERT INTO day (name) VALUES ('SATURDAY');
INSERT INTO day (name) VALUES ('SUNDAY');